
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Aug 25 19:43:35 CEST 2024
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CONST = 14;
  public static final int CHAR = 5;
  public static final int NAMESPACE = 16;
  public static final int NOTEQUAL = 24;
  public static final int LPAREN = 41;
  public static final int CONTINUE = 38;
  public static final int GREATER = 25;
  public static final int FOR = 35;
  public static final int LESS = 27;
  public static final int MINUS = 21;
  public static final int RPAREN = 42;
  public static final int STATIC = 15;
  public static final int SEMICOLON = 47;
  public static final int AND = 29;
  public static final int LESSEQUAL = 28;
  public static final int OR = 30;
  public static final int COMMA = 48;
  public static final int BOOL = 6;
  public static final int CLASS = 8;
  public static final int INC = 31;
  public static final int DIV = 18;
  public static final int PLUS = 20;
  public static final int IF = 33;
  public static final int DOT = 50;
  public static final int EOF = 0;
  public static final int RETURN = 13;
  public static final int EQUAL = 22;
  public static final int NEW = 9;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MUL = 17;
  public static final int NUMBER = 4;
  public static final int MOD = 19;
  public static final int BREAK = 37;
  public static final int IDENT = 3;
  public static final int VOID = 10;
  public static final int GREATEREQUAL = 26;
  public static final int COLON = 49;
  public static final int FOREACH = 39;
  public static final int LBRACE = 43;
  public static final int ELSE = 34;
  public static final int LSQUARE = 45;
  public static final int READ = 11;
  public static final int RSQUARE = 46;
  public static final int WHILE = 36;
  public static final int DOUBLEEQUAL = 23;
  public static final int RBRACE = 44;
  public static final int CONCLUSION = 40;
  public static final int EXTENDS = 7;
  public static final int DEC = 32;
  public static final int PRINT = 12;
}

